nmct.ssa.webapp/Controllers/VerenigingController.cs
using nmct.ba.cashlessproject.model.Web;
using nmct.ssa.webapp.DataAcces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace nmct.ssa.webapp.Controllers
{
    [Authorize]
    public class VerenigingController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            List<Vereniging> verenigingen = new List<Vereniging>();
            verenigingen = VerenigingDA.GetVerenigingen();
            return View(verenigingen);
        }

        [HttpGet]
        public ActionResult Nieuw()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Nieuw(Vereniging vereniging)
        {
            int rowsaffected = VerenigingDA.NieuweVereniging(vereniging);
            if (rowsaffected == 0)
                return View("Error");

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Bewerken(int? id)
        {
            if (!id.HasValue)
                return RedirectToAction("Index");

            Vereniging vereniging = new Vereniging();
            vereniging = VerenigingDA.GetVerenigingById(id.Value);

            return View(vereniging);
        }

        [HttpPost]
        public ActionResult Bewerken(Vereniging vereniging)
        {
            int rowsaffected = VerenigingDA.UpdateVereniging(vereniging);
            if (rowsaffected == 0)
                return View("Error");

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (!id.HasValue)
                return RedirectToAction("Index");

            Vereniging vereniging = new Vereniging();
            vereniging = VerenigingDA.GetVerenigingById(id.Value);

            return View(vereniging);
        }

    }
}

nmct.ssa.webapp/Views/Vereniging/Bewerken.cshtml
@model nmct.ba.cashlessproject.model.Web.Vereniging
@{
    ViewBag.Title = "Vereniging bewerken";
}
<h2>Vereniging bewerken</h2>
@using (Html.BeginForm("Bewerken", "Vereniging"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        <div class="form-group">
            @Html.LabelFor(model => model.Login, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Login, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Login, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.DbName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DbName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DbName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.DbLogin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DbLogin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DbLogin, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.DbPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DbPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DbPassword, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.OrganisationName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrganisationName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrganisationName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <a class="control-label col-md-2" href="/Vereniging/Index">Terug naar overzicht</a>
            <div class="col-md-10">
                <input type="submit" value="Vereniging bewerken" class="btn btn-primary" />
            </div>
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

nmct.ssa.webapp/Views/Vereniging/Details.cshtml
@model nmct.ba.cashlessproject.model.Web.Vereniging
@{
    ViewBag.Title = "Details";
}
<h2>Details van @Model.OrganisationName</h2>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DbName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DbName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DbLogin)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DbLogin)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DbPassword)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DbPassword)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OrganisationName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrganisationName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
    </dl>
    <hr />
</div>
<p><a class="btn btn-primary" href="/Vereniging/Index">Terug naar overzicht</a></p>

nmct.ssa.webapp/Views/Vereniging/Index.cshtml
@model IEnumerable<nmct.ba.cashlessproject.model.Web.Vereniging>
@{
    ViewBag.Title = "Verenigingen";
}
<h2>Verenigingen Overzicht</h2>
<br />
<p><a class="btn btn-primary" href="/Vereniging/Nieuw">Maak een nieuwe vereniging</a></p>
<br />
<table class="table table-striped">
    <tr>
        <th class="col-md-1">Organisatie</th>
        <th class="col-md-1">Adres</th>
        <th class="col-md-1">Email</th>
        <th class="col-md-1">Actie</th>
    </tr>
    @foreach (nmct.ba.cashlessproject.model.Web.Vereniging ver in @Model)
    {
        <tr>
            <td class="col-md-1">@ver.OrganisationName</td>
            <td class="col-md-1">@ver.Address</td>
            <td class="col-md-1">@ver.Email</td>
            <td class="col-md-1"><a href="/Vereniging/Bewerken/@ver.Id">Bewerken</a> | <a href="/Vereniging/Details/@ver.Id">Details</a></td>
        </tr>
    }
</table>

nmct.ssa.webapp/Views/Vereniging/Nieuw.cshtml
@model nmct.ba.cashlessproject.model.Web.Vereniging
@{
    ViewBag.Title = "Nieuwe Vereniging";
}
<h2>Nieuwe Vereniging</h2>
@using (Html.BeginForm("Nieuw", "Vereniging"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Login, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Login, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Login, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.DbName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.DbName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DbName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.DbLogin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DbLogin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DbLogin, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.DbPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DbPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DbPassword, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.OrganisationName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrganisationName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrganisationName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <a class="control-label col-md-2" href="/Vereniging/Index">Terug naar overzicht</a>
            <div class="col-md-10">
                <input type="submit" value="Maak vereniging" class="btn btn-primary" />
            </div>
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}